/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface PlatformStats {
  'verified_workers' : bigint,
  'total_seekers' : bigint,
  'avg_hourly_rate' : bigint,
  'total_workers' : bigint,
  'pending_workers' : bigint,
  'removed_workers' : bigint,
  'top_professions' : Array<ProfessionCount>,
}
export type Profession = { 'SecurityGuard' : null } |
  { 'Driver' : null } |
  { 'Cook' : null } |
  { 'Peon' : null } |
  { 'Gardner' : null } |
  { 'Welder' : null } |
  { 'Helper' : null } |
  { 'EventHelper' : null } |
  { 'Scaffolding' : null } |
  { 'Mechanic' : null } |
  { 'Electrician' : null } |
  { 'RoofWorker' : null } |
  { 'ACTechnician' : null } |
  { 'HeavyEquipmentOperator' : null } |
  { 'Cleaner' : null } |
  { 'Sweeper' : null } |
  { 'Painter' : null } |
  { 'Barber' : null } |
  { 'Loader' : null } |
  { 'Mason' : null } |
  { 'TileLayer' : null } |
  { 'Carpenter' : null } |
  { 'Mover' : null } |
  { 'SteelFixer' : null } |
  { 'Tailor' : null } |
  { 'PestControl' : null } |
  { 'DemolitionWorker' : null } |
  { 'Other' : null } |
  { 'DeliveryWorker' : null } |
  { 'Caretaker' : null } |
  { 'Plumber' : null } |
  { 'Watchman' : null } |
  { 'GlassFitter' : null } |
  { 'Washer' : null } |
  { 'RoadWorker' : null };
export interface ProfessionCount { 'count' : bigint, 'profession' : Profession }
export type SeekerId = Principal;
export interface SeekerProfile {
  'id' : SeekerId,
  'password' : string,
  'name' : string,
  'created_at' : Timestamp,
  'email' : string,
  'is_active' : boolean,
  'phone' : string,
}
export interface SeekerRegistration {
  'password' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type Timestamp = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'Rejected' : null } |
  { 'Removed' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface WorkerAvailability { 'startTime' : string, 'endTime' : string }
export type WorkerId = Principal;
export interface WorkerProfile {
  'id' : WorkerId,
  'bio' : [] | [string],
  'profile_photo' : [] | [ExternalBlob],
  'payment_preference' : [] | [string],
  'password' : string,
  'name' : string,
  'profession' : Profession,
  'approved_at' : [] | [Timestamp],
  'created_at' : Timestamp,
  'email' : string,
  'verification_status' : VerificationStatus,
  'availability' : WorkerAvailability,
  'hourly_rate' : bigint,
  'emergency_contact_name' : [] | [string],
  'languages_spoken' : [] | [Array<string>],
  'is_available' : boolean,
  'profession_custom' : [] | [string],
  'admin_notes' : [] | [string],
  'emergency_contact_phone' : [] | [string],
  'rejection_reason' : [] | [string],
  'phone' : string,
  'location_lat' : number,
  'location_lng' : number,
  'location_address' : string,
  'skills' : Array<string>,
  'years_of_experience' : [] | [bigint],
}
export interface WorkerPublic {
  'id' : WorkerId,
  'profile_photo' : [] | [ExternalBlob],
  'name' : string,
  'profession' : Profession,
  'approved_at' : [] | [Timestamp],
  'verification_status' : VerificationStatus,
  'availability' : WorkerAvailability,
  'hourly_rate' : bigint,
  'is_available' : boolean,
  'profession_custom' : [] | [string],
  'phone' : string,
  'location_lat' : number,
  'location_lng' : number,
  'location_address' : string,
  'skills' : Array<string>,
  'distance_km' : [] | [number],
}
export interface WorkerRegistration {
  'bio' : [] | [string],
  'profile_photo' : [] | [ExternalBlob],
  'payment_preference' : [] | [string],
  'password' : string,
  'name' : string,
  'profession' : Profession,
  'email' : string,
  'availability' : WorkerAvailability,
  'hourly_rate' : bigint,
  'emergency_contact_name' : [] | [string],
  'languages_spoken' : [] | [Array<string>],
  'profession_custom' : [] | [string],
  'emergency_contact_phone' : [] | [string],
  'phone' : string,
  'location_lat' : number,
  'location_lng' : number,
  'location_address' : string,
  'skills' : Array<string>,
  'years_of_experience' : [] | [bigint],
}
export interface WorkerUpdate {
  'bio' : [] | [string],
  'profile_photo' : [] | [ExternalBlob],
  'payment_preference' : [] | [string],
  'name' : string,
  'profession' : Profession,
  'email' : string,
  'availability' : WorkerAvailability,
  'hourly_rate' : bigint,
  'emergency_contact_name' : [] | [string],
  'languages_spoken' : [] | [Array<string>],
  'profession_custom' : [] | [string],
  'emergency_contact_phone' : [] | [string],
  'phone' : string,
  'location_lat' : number,
  'location_lng' : number,
  'location_address' : string,
  'skills' : Array<string>,
  'years_of_experience' : [] | [bigint],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : { 'name' : string, 'email' : string } } |
      { 'err' : string }
  >,
  'approveWorker' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyWorkerProfile' : ActorMethod<[], [] | [WorkerProfile]>,
  'getNearbyWorkers' : ActorMethod<
    [
      number,
      number,
      number,
      [] | [Profession],
      [] | [{ 'startTime' : string, 'endTime' : string }],
    ],
    Array<WorkerPublic>
  >,
  'getPendingWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'getRecentVerifiedWorkers' : ActorMethod<[bigint], Array<WorkerPublic>>,
  'getRemovedWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'getSeekerProfile' : ActorMethod<[], [] | [SeekerProfile]>,
  'getStats' : ActorMethod<[], PlatformStats>,
  'getVerifiedWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'getWorkerById' : ActorMethod<[Principal], [] | [WorkerPublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'registerSeeker' : ActorMethod<[SeekerRegistration], SeekerProfile>,
  'registerWorker' : ActorMethod<[WorkerRegistration], WorkerProfile>,
  'rejectWorker' : ActorMethod<[Principal, string], undefined>,
  'removeWorker' : ActorMethod<[Principal, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'restoreWorker' : ActorMethod<[Principal], undefined>,
  'seekerLogin' : ActorMethod<
    [string, string],
    { 'ok' : { 'id' : string, 'name' : string, 'email' : string } } |
      { 'err' : string }
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'toggleAvailability' : ActorMethod<[], boolean>,
  'updateAdminNotes' : ActorMethod<[Principal, string], undefined>,
  'updateWorkerProfile' : ActorMethod<[WorkerUpdate], WorkerProfile>,
  'workerLogin' : ActorMethod<
    [string, string],
    {
        'ok' : {
          'id' : string,
          'name' : string,
          'profession' : string,
          'email' : string,
          'verification_status' : string,
        }
      } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];