/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkerId = IDL.Principal;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profession = IDL.Variant({
  'SecurityGuard' : IDL.Null,
  'Driver' : IDL.Null,
  'Cook' : IDL.Null,
  'Peon' : IDL.Null,
  'Gardner' : IDL.Null,
  'Welder' : IDL.Null,
  'Helper' : IDL.Null,
  'EventHelper' : IDL.Null,
  'Scaffolding' : IDL.Null,
  'Mechanic' : IDL.Null,
  'Electrician' : IDL.Null,
  'RoofWorker' : IDL.Null,
  'ACTechnician' : IDL.Null,
  'HeavyEquipmentOperator' : IDL.Null,
  'Cleaner' : IDL.Null,
  'Sweeper' : IDL.Null,
  'Painter' : IDL.Null,
  'Barber' : IDL.Null,
  'Loader' : IDL.Null,
  'Mason' : IDL.Null,
  'TileLayer' : IDL.Null,
  'Carpenter' : IDL.Null,
  'Mover' : IDL.Null,
  'SteelFixer' : IDL.Null,
  'Tailor' : IDL.Null,
  'PestControl' : IDL.Null,
  'DemolitionWorker' : IDL.Null,
  'Other' : IDL.Null,
  'DeliveryWorker' : IDL.Null,
  'Caretaker' : IDL.Null,
  'Plumber' : IDL.Null,
  'Watchman' : IDL.Null,
  'GlassFitter' : IDL.Null,
  'Washer' : IDL.Null,
  'RoadWorker' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const VerificationStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Removed' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WorkerAvailability = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
});
export const WorkerProfile = IDL.Record({
  'id' : WorkerId,
  'bio' : IDL.Opt(IDL.Text),
  'profile_photo' : IDL.Opt(ExternalBlob),
  'payment_preference' : IDL.Opt(IDL.Text),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'profession' : Profession,
  'approved_at' : IDL.Opt(Timestamp),
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'verification_status' : VerificationStatus,
  'availability' : WorkerAvailability,
  'hourly_rate' : IDL.Nat,
  'emergency_contact_name' : IDL.Opt(IDL.Text),
  'languages_spoken' : IDL.Opt(IDL.Vec(IDL.Text)),
  'is_available' : IDL.Bool,
  'profession_custom' : IDL.Opt(IDL.Text),
  'admin_notes' : IDL.Opt(IDL.Text),
  'emergency_contact_phone' : IDL.Opt(IDL.Text),
  'rejection_reason' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'location_lat' : IDL.Float64,
  'location_lng' : IDL.Float64,
  'location_address' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'years_of_experience' : IDL.Opt(IDL.Nat),
});
export const WorkerPublic = IDL.Record({
  'id' : WorkerId,
  'profile_photo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'profession' : Profession,
  'approved_at' : IDL.Opt(Timestamp),
  'verification_status' : VerificationStatus,
  'availability' : WorkerAvailability,
  'hourly_rate' : IDL.Nat,
  'is_available' : IDL.Bool,
  'profession_custom' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'location_lat' : IDL.Float64,
  'location_lng' : IDL.Float64,
  'location_address' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'distance_km' : IDL.Opt(IDL.Float64),
});
export const SeekerId = IDL.Principal;
export const SeekerProfile = IDL.Record({
  'id' : SeekerId,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'is_active' : IDL.Bool,
  'phone' : IDL.Text,
});
export const ProfessionCount = IDL.Record({
  'count' : IDL.Nat,
  'profession' : Profession,
});
export const PlatformStats = IDL.Record({
  'verified_workers' : IDL.Nat,
  'total_seekers' : IDL.Nat,
  'avg_hourly_rate' : IDL.Nat,
  'total_workers' : IDL.Nat,
  'pending_workers' : IDL.Nat,
  'removed_workers' : IDL.Nat,
  'top_professions' : IDL.Vec(ProfessionCount),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const SeekerRegistration = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const WorkerRegistration = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'profile_photo' : IDL.Opt(ExternalBlob),
  'payment_preference' : IDL.Opt(IDL.Text),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'profession' : Profession,
  'email' : IDL.Text,
  'availability' : WorkerAvailability,
  'hourly_rate' : IDL.Nat,
  'emergency_contact_name' : IDL.Opt(IDL.Text),
  'languages_spoken' : IDL.Opt(IDL.Vec(IDL.Text)),
  'profession_custom' : IDL.Opt(IDL.Text),
  'emergency_contact_phone' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'location_lat' : IDL.Float64,
  'location_lng' : IDL.Float64,
  'location_address' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'years_of_experience' : IDL.Opt(IDL.Nat),
});
export const WorkerUpdate = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'profile_photo' : IDL.Opt(ExternalBlob),
  'payment_preference' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'profession' : Profession,
  'email' : IDL.Text,
  'availability' : WorkerAvailability,
  'hourly_rate' : IDL.Nat,
  'emergency_contact_name' : IDL.Opt(IDL.Text),
  'languages_spoken' : IDL.Opt(IDL.Vec(IDL.Text)),
  'profession_custom' : IDL.Opt(IDL.Text),
  'emergency_contact_phone' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'location_lat' : IDL.Float64,
  'location_lng' : IDL.Float64,
  'location_address' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'years_of_experience' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'approveWorker' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
  'getNearbyWorkers' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(Profession),
        IDL.Opt(IDL.Record({ 'startTime' : IDL.Text, 'endTime' : IDL.Text })),
      ],
      [IDL.Vec(WorkerPublic)],
      ['query'],
    ),
  'getPendingWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getRecentVerifiedWorkers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WorkerPublic)],
      ['query'],
    ),
  'getRemovedWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getSeekerProfile' : IDL.Func([], [IDL.Opt(SeekerProfile)], ['query']),
  'getStats' : IDL.Func([], [PlatformStats], ['query']),
  'getVerifiedWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getWorkerById' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WorkerPublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'registerSeeker' : IDL.Func([SeekerRegistration], [SeekerProfile], []),
  'registerWorker' : IDL.Func([WorkerRegistration], [WorkerProfile], []),
  'rejectWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'removeWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'restoreWorker' : IDL.Func([IDL.Principal], [], []),
  'seekerLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'id' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'toggleAvailability' : IDL.Func([], [IDL.Bool], []),
  'updateAdminNotes' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateWorkerProfile' : IDL.Func([WorkerUpdate], [WorkerProfile], []),
  'workerLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'id' : IDL.Text,
            'name' : IDL.Text,
            'profession' : IDL.Text,
            'email' : IDL.Text,
            'verification_status' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkerId = IDL.Principal;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profession = IDL.Variant({
    'SecurityGuard' : IDL.Null,
    'Driver' : IDL.Null,
    'Cook' : IDL.Null,
    'Peon' : IDL.Null,
    'Gardner' : IDL.Null,
    'Welder' : IDL.Null,
    'Helper' : IDL.Null,
    'EventHelper' : IDL.Null,
    'Scaffolding' : IDL.Null,
    'Mechanic' : IDL.Null,
    'Electrician' : IDL.Null,
    'RoofWorker' : IDL.Null,
    'ACTechnician' : IDL.Null,
    'HeavyEquipmentOperator' : IDL.Null,
    'Cleaner' : IDL.Null,
    'Sweeper' : IDL.Null,
    'Painter' : IDL.Null,
    'Barber' : IDL.Null,
    'Loader' : IDL.Null,
    'Mason' : IDL.Null,
    'TileLayer' : IDL.Null,
    'Carpenter' : IDL.Null,
    'Mover' : IDL.Null,
    'SteelFixer' : IDL.Null,
    'Tailor' : IDL.Null,
    'PestControl' : IDL.Null,
    'DemolitionWorker' : IDL.Null,
    'Other' : IDL.Null,
    'DeliveryWorker' : IDL.Null,
    'Caretaker' : IDL.Null,
    'Plumber' : IDL.Null,
    'Watchman' : IDL.Null,
    'GlassFitter' : IDL.Null,
    'Washer' : IDL.Null,
    'RoadWorker' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const VerificationStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Removed' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WorkerAvailability = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
  });
  const WorkerProfile = IDL.Record({
    'id' : WorkerId,
    'bio' : IDL.Opt(IDL.Text),
    'profile_photo' : IDL.Opt(ExternalBlob),
    'payment_preference' : IDL.Opt(IDL.Text),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'profession' : Profession,
    'approved_at' : IDL.Opt(Timestamp),
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'verification_status' : VerificationStatus,
    'availability' : WorkerAvailability,
    'hourly_rate' : IDL.Nat,
    'emergency_contact_name' : IDL.Opt(IDL.Text),
    'languages_spoken' : IDL.Opt(IDL.Vec(IDL.Text)),
    'is_available' : IDL.Bool,
    'profession_custom' : IDL.Opt(IDL.Text),
    'admin_notes' : IDL.Opt(IDL.Text),
    'emergency_contact_phone' : IDL.Opt(IDL.Text),
    'rejection_reason' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'location_lat' : IDL.Float64,
    'location_lng' : IDL.Float64,
    'location_address' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'years_of_experience' : IDL.Opt(IDL.Nat),
  });
  const WorkerPublic = IDL.Record({
    'id' : WorkerId,
    'profile_photo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'profession' : Profession,
    'approved_at' : IDL.Opt(Timestamp),
    'verification_status' : VerificationStatus,
    'availability' : WorkerAvailability,
    'hourly_rate' : IDL.Nat,
    'is_available' : IDL.Bool,
    'profession_custom' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'location_lat' : IDL.Float64,
    'location_lng' : IDL.Float64,
    'location_address' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'distance_km' : IDL.Opt(IDL.Float64),
  });
  const SeekerId = IDL.Principal;
  const SeekerProfile = IDL.Record({
    'id' : SeekerId,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'is_active' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const ProfessionCount = IDL.Record({
    'count' : IDL.Nat,
    'profession' : Profession,
  });
  const PlatformStats = IDL.Record({
    'verified_workers' : IDL.Nat,
    'total_seekers' : IDL.Nat,
    'avg_hourly_rate' : IDL.Nat,
    'total_workers' : IDL.Nat,
    'pending_workers' : IDL.Nat,
    'removed_workers' : IDL.Nat,
    'top_professions' : IDL.Vec(ProfessionCount),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const SeekerRegistration = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const WorkerRegistration = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'profile_photo' : IDL.Opt(ExternalBlob),
    'payment_preference' : IDL.Opt(IDL.Text),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'profession' : Profession,
    'email' : IDL.Text,
    'availability' : WorkerAvailability,
    'hourly_rate' : IDL.Nat,
    'emergency_contact_name' : IDL.Opt(IDL.Text),
    'languages_spoken' : IDL.Opt(IDL.Vec(IDL.Text)),
    'profession_custom' : IDL.Opt(IDL.Text),
    'emergency_contact_phone' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'location_lat' : IDL.Float64,
    'location_lng' : IDL.Float64,
    'location_address' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'years_of_experience' : IDL.Opt(IDL.Nat),
  });
  const WorkerUpdate = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'profile_photo' : IDL.Opt(ExternalBlob),
    'payment_preference' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'profession' : Profession,
    'email' : IDL.Text,
    'availability' : WorkerAvailability,
    'hourly_rate' : IDL.Nat,
    'emergency_contact_name' : IDL.Opt(IDL.Text),
    'languages_spoken' : IDL.Opt(IDL.Vec(IDL.Text)),
    'profession_custom' : IDL.Opt(IDL.Text),
    'emergency_contact_phone' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'location_lat' : IDL.Float64,
    'location_lng' : IDL.Float64,
    'location_address' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'years_of_experience' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'approveWorker' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
    'getNearbyWorkers' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(Profession),
          IDL.Opt(IDL.Record({ 'startTime' : IDL.Text, 'endTime' : IDL.Text })),
        ],
        [IDL.Vec(WorkerPublic)],
        ['query'],
      ),
    'getPendingWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getRecentVerifiedWorkers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WorkerPublic)],
        ['query'],
      ),
    'getRemovedWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getSeekerProfile' : IDL.Func([], [IDL.Opt(SeekerProfile)], ['query']),
    'getStats' : IDL.Func([], [PlatformStats], ['query']),
    'getVerifiedWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getWorkerById' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WorkerPublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'registerSeeker' : IDL.Func([SeekerRegistration], [SeekerProfile], []),
    'registerWorker' : IDL.Func([WorkerRegistration], [WorkerProfile], []),
    'rejectWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'removeWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'restoreWorker' : IDL.Func([IDL.Principal], [], []),
    'seekerLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'id' : IDL.Text,
              'name' : IDL.Text,
              'email' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'toggleAvailability' : IDL.Func([], [IDL.Bool], []),
    'updateAdminNotes' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateWorkerProfile' : IDL.Func([WorkerUpdate], [WorkerProfile], []),
    'workerLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'id' : IDL.Text,
              'name' : IDL.Text,
              'profession' : IDL.Text,
              'email' : IDL.Text,
              'verification_status' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };