/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface WorkerUpdate {
    bio?: string;
    profile_photo?: ExternalBlob;
    payment_preference?: string;
    name: string;
    profession: Profession;
    email: string;
    availability: WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name?: string;
    languages_spoken?: Array<string>;
    profession_custom?: string;
    emergency_contact_phone?: string;
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience?: bigint;
}
export interface WorkerAvailability {
    startTime: string;
    endTime: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface SeekerRegistration {
    password: string;
    name: string;
    email: string;
    phone: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface WorkerProfile {
    id: WorkerId;
    bio?: string;
    profile_photo?: ExternalBlob;
    payment_preference?: string;
    password: string;
    name: string;
    profession: Profession;
    approved_at?: Timestamp;
    created_at: Timestamp;
    email: string;
    verification_status: VerificationStatus;
    availability: WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name?: string;
    languages_spoken?: Array<string>;
    is_available: boolean;
    profession_custom?: string;
    admin_notes?: string;
    emergency_contact_phone?: string;
    rejection_reason?: string;
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience?: bigint;
}
export interface ProfessionCount {
    count: bigint;
    profession: Profession;
}
export interface SeekerProfile {
    id: SeekerId;
    password: string;
    name: string;
    created_at: Timestamp;
    email: string;
    is_active: boolean;
    phone: string;
}
export type WorkerId = Principal;
export interface WorkerRegistration {
    bio?: string;
    profile_photo?: ExternalBlob;
    payment_preference?: string;
    password: string;
    name: string;
    profession: Profession;
    email: string;
    availability: WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name?: string;
    languages_spoken?: Array<string>;
    profession_custom?: string;
    emergency_contact_phone?: string;
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience?: bigint;
}
export interface PlatformStats {
    verified_workers: bigint;
    total_seekers: bigint;
    avg_hourly_rate: bigint;
    total_workers: bigint;
    pending_workers: bigint;
    removed_workers: bigint;
    top_professions: Array<ProfessionCount>;
}
export type SeekerId = Principal;
export interface WorkerPublic {
    id: WorkerId;
    profile_photo?: ExternalBlob;
    name: string;
    profession: Profession;
    approved_at?: Timestamp;
    verification_status: VerificationStatus;
    availability: WorkerAvailability;
    hourly_rate: bigint;
    is_available: boolean;
    profession_custom?: string;
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    distance_km?: number;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Profession {
    SecurityGuard = "SecurityGuard",
    Driver = "Driver",
    Cook = "Cook",
    Peon = "Peon",
    Gardner = "Gardner",
    Welder = "Welder",
    Helper = "Helper",
    EventHelper = "EventHelper",
    Scaffolding = "Scaffolding",
    Mechanic = "Mechanic",
    Electrician = "Electrician",
    RoofWorker = "RoofWorker",
    ACTechnician = "ACTechnician",
    HeavyEquipmentOperator = "HeavyEquipmentOperator",
    Cleaner = "Cleaner",
    Sweeper = "Sweeper",
    Painter = "Painter",
    Barber = "Barber",
    Loader = "Loader",
    Mason = "Mason",
    TileLayer = "TileLayer",
    Carpenter = "Carpenter",
    Mover = "Mover",
    SteelFixer = "SteelFixer",
    Tailor = "Tailor",
    PestControl = "PestControl",
    DemolitionWorker = "DemolitionWorker",
    Other = "Other",
    DeliveryWorker = "DeliveryWorker",
    Caretaker = "Caretaker",
    Plumber = "Plumber",
    Watchman = "Watchman",
    GlassFitter = "GlassFitter",
    Washer = "Washer",
    RoadWorker = "RoadWorker"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VerificationStatus {
    Rejected = "Rejected",
    Removed = "Removed",
    Verified = "Verified",
    Pending = "Pending"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    adminLogin(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: {
            name: string;
            email: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    approveWorker(workerId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getMyWorkerProfile(): Promise<WorkerProfile | null>;
    getNearbyWorkers(lat: number, lng: number, radius_km: number, profession: Profession | null, availabilityFilter: {
        startTime: string;
        endTime: string;
    } | null): Promise<Array<WorkerPublic>>;
    getPendingWorkers(): Promise<Array<WorkerProfile>>;
    getRecentVerifiedWorkers(limit: bigint): Promise<Array<WorkerPublic>>;
    getRemovedWorkers(): Promise<Array<WorkerProfile>>;
    getSeekerProfile(): Promise<SeekerProfile | null>;
    getStats(): Promise<PlatformStats>;
    getVerifiedWorkers(): Promise<Array<WorkerProfile>>;
    getWorkerById(id: Principal): Promise<WorkerPublic | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    registerSeeker(reg: SeekerRegistration): Promise<SeekerProfile>;
    registerWorker(reg: WorkerRegistration): Promise<WorkerProfile>;
    rejectWorker(workerId: Principal, reason: string): Promise<void>;
    removeWorker(workerId: Principal, reason: string): Promise<void>;
    requestApproval(): Promise<void>;
    restoreWorker(workerId: Principal): Promise<void>;
    seekerLogin(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: {
            id: string;
            name: string;
            email: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    toggleAvailability(): Promise<boolean>;
    updateAdminNotes(workerId: Principal, notes: string): Promise<void>;
    updateWorkerProfile(upd: WorkerUpdate): Promise<WorkerProfile>;
    workerLogin(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: {
            id: string;
            name: string;
            profession: string;
            email: string;
            verification_status: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { ApprovalStatus as _ApprovalStatus, ExternalBlob as _ExternalBlob, PlatformStats as _PlatformStats, Profession as _Profession, ProfessionCount as _ProfessionCount, SeekerProfile as _SeekerProfile, Timestamp as _Timestamp, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, VerificationStatus as _VerificationStatus, WorkerAvailability as _WorkerAvailability, WorkerId as _WorkerId, WorkerProfile as _WorkerProfile, WorkerPublic as _WorkerPublic, WorkerRegistration as _WorkerRegistration, WorkerUpdate as _WorkerUpdate, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            name: string;
            email: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveWorker(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWorker(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkerProfile(): Promise<WorkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkerProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkerProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearbyWorkers(arg0: number, arg1: number, arg2: number, arg3: Profession | null, arg4: {
        startTime: string;
        endTime: string;
    } | null): Promise<Array<WorkerPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyWorkers(arg0, arg1, arg2, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyWorkers(arg0, arg1, arg2, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingWorkers(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingWorkers();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingWorkers();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentVerifiedWorkers(arg0: bigint): Promise<Array<WorkerPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentVerifiedWorkers(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentVerifiedWorkers(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRemovedWorkers(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemovedWorkers();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemovedWorkers();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeekerProfile(): Promise<SeekerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeekerProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeekerProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return from_candid_PlatformStats_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return from_candid_PlatformStats_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedWorkers(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedWorkers();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedWorkers();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerById(arg0: Principal): Promise<WorkerPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerById(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerById(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerSeeker(arg0: SeekerRegistration): Promise<SeekerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSeeker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSeeker(arg0);
            return result;
        }
    }
    async registerWorker(arg0: WorkerRegistration): Promise<WorkerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWorker(await to_candid_WorkerRegistration_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_WorkerProfile_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWorker(await to_candid_WorkerRegistration_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_WorkerProfile_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectWorker(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWorker(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWorker(arg0, arg1);
            return result;
        }
    }
    async removeWorker(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorker(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorker(arg0, arg1);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async restoreWorker(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreWorker(arg0);
            return result;
        }
    }
    async seekerLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            id: string;
            name: string;
            email: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.seekerLogin(arg0, arg1);
                return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seekerLogin(arg0, arg1);
            return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async toggleAvailability(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAvailability();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAvailability();
            return result;
        }
    }
    async updateAdminNotes(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminNotes(arg0, arg1);
            return result;
        }
    }
    async updateWorkerProfile(arg0: WorkerUpdate): Promise<WorkerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkerProfile(await to_candid_WorkerUpdate_n52(this._uploadFile, this._downloadFile, arg0));
                return from_candid_WorkerProfile_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkerProfile(await to_candid_WorkerUpdate_n52(this._uploadFile, this._downloadFile, arg0));
            return from_candid_WorkerProfile_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async workerLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            id: string;
            name: string;
            profession: string;
            email: string;
            verification_status: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.workerLogin(arg0, arg1);
                return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.workerLogin(arg0, arg1);
            return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PlatformStats_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformStats): PlatformStats {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ProfessionCount_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfessionCount): ProfessionCount {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Profession_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profession): Profession {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_WorkerProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerProfile): Promise<WorkerProfile> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_WorkerPublic_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerPublic): Promise<WorkerPublic> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkerProfile]): Promise<WorkerProfile | null> {
    return value.length === 0 ? null : await from_candid_WorkerProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SeekerProfile]): SeekerProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkerPublic]): Promise<WorkerPublic | null> {
    return value.length === 0 ? null : await from_candid_WorkerPublic_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkerId;
    bio: [] | [string];
    profile_photo: [] | [_ExternalBlob];
    payment_preference: [] | [string];
    password: string;
    name: string;
    profession: _Profession;
    approved_at: [] | [_Timestamp];
    created_at: _Timestamp;
    email: string;
    verification_status: _VerificationStatus;
    availability: _WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name: [] | [string];
    languages_spoken: [] | [Array<string>];
    is_available: boolean;
    profession_custom: [] | [string];
    admin_notes: [] | [string];
    emergency_contact_phone: [] | [string];
    rejection_reason: [] | [string];
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience: [] | [bigint];
}): Promise<{
    id: WorkerId;
    bio?: string;
    profile_photo?: ExternalBlob;
    payment_preference?: string;
    password: string;
    name: string;
    profession: Profession;
    approved_at?: Timestamp;
    created_at: Timestamp;
    email: string;
    verification_status: VerificationStatus;
    availability: WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name?: string;
    languages_spoken?: Array<string>;
    is_available: boolean;
    profession_custom?: string;
    admin_notes?: string;
    emergency_contact_phone?: string;
    rejection_reason?: string;
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience?: bigint;
}> {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.bio)),
        profile_photo: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.profile_photo)),
        payment_preference: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.payment_preference)),
        password: value.password,
        name: value.name,
        profession: from_candid_Profession_n19(_uploadFile, _downloadFile, value.profession),
        approved_at: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.approved_at)),
        created_at: value.created_at,
        email: value.email,
        verification_status: from_candid_VerificationStatus_n22(_uploadFile, _downloadFile, value.verification_status),
        availability: value.availability,
        hourly_rate: value.hourly_rate,
        emergency_contact_name: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.emergency_contact_name)),
        languages_spoken: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.languages_spoken)),
        is_available: value.is_available,
        profession_custom: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.profession_custom)),
        admin_notes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.admin_notes)),
        emergency_contact_phone: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.emergency_contact_phone)),
        rejection_reason: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rejection_reason)),
        phone: value.phone,
        location_lat: value.location_lat,
        location_lng: value.location_lng,
        location_address: value.location_address,
        skills: value.skills,
        years_of_experience: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.years_of_experience))
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkerId;
    profile_photo: [] | [_ExternalBlob];
    name: string;
    profession: _Profession;
    approved_at: [] | [_Timestamp];
    verification_status: _VerificationStatus;
    availability: _WorkerAvailability;
    hourly_rate: bigint;
    is_available: boolean;
    profession_custom: [] | [string];
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    distance_km: [] | [number];
}): Promise<{
    id: WorkerId;
    profile_photo?: ExternalBlob;
    name: string;
    profession: Profession;
    approved_at?: Timestamp;
    verification_status: VerificationStatus;
    availability: WorkerAvailability;
    hourly_rate: bigint;
    is_available: boolean;
    profession_custom?: string;
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    distance_km?: number;
}> {
    return {
        id: value.id,
        profile_photo: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.profile_photo)),
        name: value.name,
        profession: from_candid_Profession_n19(_uploadFile, _downloadFile, value.profession),
        approved_at: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.approved_at)),
        verification_status: from_candid_VerificationStatus_n22(_uploadFile, _downloadFile, value.verification_status),
        availability: value.availability,
        hourly_rate: value.hourly_rate,
        is_available: value.is_available,
        profession_custom: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.profession_custom)),
        phone: value.phone,
        location_lat: value.location_lat,
        location_lng: value.location_lng,
        location_address: value.location_address,
        skills: value.skills,
        distance_km: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.distance_km))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified_workers: bigint;
    total_seekers: bigint;
    avg_hourly_rate: bigint;
    total_workers: bigint;
    pending_workers: bigint;
    removed_workers: bigint;
    top_professions: Array<_ProfessionCount>;
}): {
    verified_workers: bigint;
    total_seekers: bigint;
    avg_hourly_rate: bigint;
    total_workers: bigint;
    pending_workers: bigint;
    removed_workers: bigint;
    top_professions: Array<ProfessionCount>;
} {
    return {
        verified_workers: value.verified_workers,
        total_seekers: value.total_seekers,
        avg_hourly_rate: value.avg_hourly_rate,
        total_workers: value.total_workers,
        pending_workers: value.pending_workers,
        removed_workers: value.removed_workers,
        top_professions: from_candid_vec_n37(_uploadFile, _downloadFile, value.top_professions)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    profession: _Profession;
}): {
    count: bigint;
    profession: Profession;
} {
    return {
        count: value.count,
        profession: from_candid_Profession_n19(_uploadFile, _downloadFile, value.profession)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n44(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SecurityGuard: null;
} | {
    Driver: null;
} | {
    Cook: null;
} | {
    Peon: null;
} | {
    Gardner: null;
} | {
    Welder: null;
} | {
    Helper: null;
} | {
    EventHelper: null;
} | {
    Scaffolding: null;
} | {
    Mechanic: null;
} | {
    Electrician: null;
} | {
    RoofWorker: null;
} | {
    ACTechnician: null;
} | {
    HeavyEquipmentOperator: null;
} | {
    Cleaner: null;
} | {
    Sweeper: null;
} | {
    Painter: null;
} | {
    Barber: null;
} | {
    Loader: null;
} | {
    Mason: null;
} | {
    TileLayer: null;
} | {
    Carpenter: null;
} | {
    Mover: null;
} | {
    SteelFixer: null;
} | {
    Tailor: null;
} | {
    PestControl: null;
} | {
    DemolitionWorker: null;
} | {
    Other: null;
} | {
    DeliveryWorker: null;
} | {
    Caretaker: null;
} | {
    Plumber: null;
} | {
    Watchman: null;
} | {
    GlassFitter: null;
} | {
    Washer: null;
} | {
    RoadWorker: null;
}): Profession {
    return "SecurityGuard" in value ? Profession.SecurityGuard : "Driver" in value ? Profession.Driver : "Cook" in value ? Profession.Cook : "Peon" in value ? Profession.Peon : "Gardner" in value ? Profession.Gardner : "Welder" in value ? Profession.Welder : "Helper" in value ? Profession.Helper : "EventHelper" in value ? Profession.EventHelper : "Scaffolding" in value ? Profession.Scaffolding : "Mechanic" in value ? Profession.Mechanic : "Electrician" in value ? Profession.Electrician : "RoofWorker" in value ? Profession.RoofWorker : "ACTechnician" in value ? Profession.ACTechnician : "HeavyEquipmentOperator" in value ? Profession.HeavyEquipmentOperator : "Cleaner" in value ? Profession.Cleaner : "Sweeper" in value ? Profession.Sweeper : "Painter" in value ? Profession.Painter : "Barber" in value ? Profession.Barber : "Loader" in value ? Profession.Loader : "Mason" in value ? Profession.Mason : "TileLayer" in value ? Profession.TileLayer : "Carpenter" in value ? Profession.Carpenter : "Mover" in value ? Profession.Mover : "SteelFixer" in value ? Profession.SteelFixer : "Tailor" in value ? Profession.Tailor : "PestControl" in value ? Profession.PestControl : "DemolitionWorker" in value ? Profession.DemolitionWorker : "Other" in value ? Profession.Other : "DeliveryWorker" in value ? Profession.DeliveryWorker : "Caretaker" in value ? Profession.Caretaker : "Plumber" in value ? Profession.Plumber : "Watchman" in value ? Profession.Watchman : "GlassFitter" in value ? Profession.GlassFitter : "Washer" in value ? Profession.Washer : "RoadWorker" in value ? Profession.RoadWorker : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Rejected: null;
} | {
    Removed: null;
} | {
    Verified: null;
} | {
    Pending: null;
}): VerificationStatus {
    return "Rejected" in value ? VerificationStatus.Rejected : "Removed" in value ? VerificationStatus.Removed : "Verified" in value ? VerificationStatus.Verified : "Pending" in value ? VerificationStatus.Pending : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        id: string;
        name: string;
        email: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        id: string;
        name: string;
        email: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        id: string;
        name: string;
        profession: string;
        email: string;
        verification_status: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        id: string;
        name: string;
        profession: string;
        email: string;
        verification_status: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        name: string;
        email: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        name: string;
        email: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerPublic>): Promise<Array<WorkerPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_WorkerPublic_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerProfile>): Promise<Array<WorkerProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_WorkerProfile_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProfessionCount>): Array<ProfessionCount> {
    return value.map((x)=>from_candid_ProfessionCount_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n42(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Profession_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profession): _Profession {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
async function to_candid_WorkerRegistration_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerRegistration): Promise<_WorkerRegistration> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_WorkerUpdate_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerUpdate): Promise<_WorkerUpdate> {
    return await to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profession | null): [] | [_Profession] {
    return value === null ? candid_none() : candid_some(to_candid_Profession_n26(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: string;
    endTime: string;
} | null): [] | [{
        startTime: string;
        endTime: string;
    }] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    profile_photo?: ExternalBlob;
    payment_preference?: string;
    password: string;
    name: string;
    profession: Profession;
    email: string;
    availability: WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name?: string;
    languages_spoken?: Array<string>;
    profession_custom?: string;
    emergency_contact_phone?: string;
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience?: bigint;
}): Promise<{
    bio: [] | [string];
    profile_photo: [] | [_ExternalBlob];
    payment_preference: [] | [string];
    password: string;
    name: string;
    profession: _Profession;
    email: string;
    availability: _WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name: [] | [string];
    languages_spoken: [] | [Array<string>];
    profession_custom: [] | [string];
    emergency_contact_phone: [] | [string];
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience: [] | [bigint];
}> {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        profile_photo: value.profile_photo ? candid_some(await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.profile_photo)) : candid_none(),
        payment_preference: value.payment_preference ? candid_some(value.payment_preference) : candid_none(),
        password: value.password,
        name: value.name,
        profession: to_candid_Profession_n26(_uploadFile, _downloadFile, value.profession),
        email: value.email,
        availability: value.availability,
        hourly_rate: value.hourly_rate,
        emergency_contact_name: value.emergency_contact_name ? candid_some(value.emergency_contact_name) : candid_none(),
        languages_spoken: value.languages_spoken ? candid_some(value.languages_spoken) : candid_none(),
        profession_custom: value.profession_custom ? candid_some(value.profession_custom) : candid_none(),
        emergency_contact_phone: value.emergency_contact_phone ? candid_some(value.emergency_contact_phone) : candid_none(),
        phone: value.phone,
        location_lat: value.location_lat,
        location_lng: value.location_lng,
        location_address: value.location_address,
        skills: value.skills,
        years_of_experience: value.years_of_experience ? candid_some(value.years_of_experience) : candid_none()
    };
}
async function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    profile_photo?: ExternalBlob;
    payment_preference?: string;
    name: string;
    profession: Profession;
    email: string;
    availability: WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name?: string;
    languages_spoken?: Array<string>;
    profession_custom?: string;
    emergency_contact_phone?: string;
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience?: bigint;
}): Promise<{
    bio: [] | [string];
    profile_photo: [] | [_ExternalBlob];
    payment_preference: [] | [string];
    name: string;
    profession: _Profession;
    email: string;
    availability: _WorkerAvailability;
    hourly_rate: bigint;
    emergency_contact_name: [] | [string];
    languages_spoken: [] | [Array<string>];
    profession_custom: [] | [string];
    emergency_contact_phone: [] | [string];
    phone: string;
    location_lat: number;
    location_lng: number;
    location_address: string;
    skills: Array<string>;
    years_of_experience: [] | [bigint];
}> {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        profile_photo: value.profile_photo ? candid_some(await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.profile_photo)) : candid_none(),
        payment_preference: value.payment_preference ? candid_some(value.payment_preference) : candid_none(),
        name: value.name,
        profession: to_candid_Profession_n26(_uploadFile, _downloadFile, value.profession),
        email: value.email,
        availability: value.availability,
        hourly_rate: value.hourly_rate,
        emergency_contact_name: value.emergency_contact_name ? candid_some(value.emergency_contact_name) : candid_none(),
        languages_spoken: value.languages_spoken ? candid_some(value.languages_spoken) : candid_none(),
        profession_custom: value.profession_custom ? candid_some(value.profession_custom) : candid_none(),
        emergency_contact_phone: value.emergency_contact_phone ? candid_some(value.emergency_contact_phone) : candid_none(),
        phone: value.phone,
        location_lat: value.location_lat,
        location_lng: value.location_lng,
        location_address: value.location_address,
        skills: value.skills,
        years_of_experience: value.years_of_experience ? candid_some(value.years_of_experience) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profession): {
    SecurityGuard: null;
} | {
    Driver: null;
} | {
    Cook: null;
} | {
    Peon: null;
} | {
    Gardner: null;
} | {
    Welder: null;
} | {
    Helper: null;
} | {
    EventHelper: null;
} | {
    Scaffolding: null;
} | {
    Mechanic: null;
} | {
    Electrician: null;
} | {
    RoofWorker: null;
} | {
    ACTechnician: null;
} | {
    HeavyEquipmentOperator: null;
} | {
    Cleaner: null;
} | {
    Sweeper: null;
} | {
    Painter: null;
} | {
    Barber: null;
} | {
    Loader: null;
} | {
    Mason: null;
} | {
    TileLayer: null;
} | {
    Carpenter: null;
} | {
    Mover: null;
} | {
    SteelFixer: null;
} | {
    Tailor: null;
} | {
    PestControl: null;
} | {
    DemolitionWorker: null;
} | {
    Other: null;
} | {
    DeliveryWorker: null;
} | {
    Caretaker: null;
} | {
    Plumber: null;
} | {
    Watchman: null;
} | {
    GlassFitter: null;
} | {
    Washer: null;
} | {
    RoadWorker: null;
} {
    return value == Profession.SecurityGuard ? {
        SecurityGuard: null
    } : value == Profession.Driver ? {
        Driver: null
    } : value == Profession.Cook ? {
        Cook: null
    } : value == Profession.Peon ? {
        Peon: null
    } : value == Profession.Gardner ? {
        Gardner: null
    } : value == Profession.Welder ? {
        Welder: null
    } : value == Profession.Helper ? {
        Helper: null
    } : value == Profession.EventHelper ? {
        EventHelper: null
    } : value == Profession.Scaffolding ? {
        Scaffolding: null
    } : value == Profession.Mechanic ? {
        Mechanic: null
    } : value == Profession.Electrician ? {
        Electrician: null
    } : value == Profession.RoofWorker ? {
        RoofWorker: null
    } : value == Profession.ACTechnician ? {
        ACTechnician: null
    } : value == Profession.HeavyEquipmentOperator ? {
        HeavyEquipmentOperator: null
    } : value == Profession.Cleaner ? {
        Cleaner: null
    } : value == Profession.Sweeper ? {
        Sweeper: null
    } : value == Profession.Painter ? {
        Painter: null
    } : value == Profession.Barber ? {
        Barber: null
    } : value == Profession.Loader ? {
        Loader: null
    } : value == Profession.Mason ? {
        Mason: null
    } : value == Profession.TileLayer ? {
        TileLayer: null
    } : value == Profession.Carpenter ? {
        Carpenter: null
    } : value == Profession.Mover ? {
        Mover: null
    } : value == Profession.SteelFixer ? {
        SteelFixer: null
    } : value == Profession.Tailor ? {
        Tailor: null
    } : value == Profession.PestControl ? {
        PestControl: null
    } : value == Profession.DemolitionWorker ? {
        DemolitionWorker: null
    } : value == Profession.Other ? {
        Other: null
    } : value == Profession.DeliveryWorker ? {
        DeliveryWorker: null
    } : value == Profession.Caretaker ? {
        Caretaker: null
    } : value == Profession.Plumber ? {
        Plumber: null
    } : value == Profession.Watchman ? {
        Watchman: null
    } : value == Profession.GlassFitter ? {
        GlassFitter: null
    } : value == Profession.Washer ? {
        Washer: null
    } : value == Profession.RoadWorker ? {
        RoadWorker: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
